// Generated by gencpp from file jaco_msgs/SetForceControlParams.msg
// DO NOT EDIT!


#ifndef JACO_MSGS_MESSAGE_SETFORCECONTROLPARAMS_H
#define JACO_MSGS_MESSAGE_SETFORCECONTROLPARAMS_H

#include <ros/service_traits.h>


#include <jaco_msgs/SetForceControlParamsRequest.h>
#include <jaco_msgs/SetForceControlParamsResponse.h>


namespace jaco_msgs
{

struct SetForceControlParams
{

typedef SetForceControlParamsRequest Request;
typedef SetForceControlParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetForceControlParams
} // namespace jaco_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jaco_msgs::SetForceControlParams > {
  static const char* value()
  {
    return "5c0999be3d1c60dba47ea0b2fd08231e";
  }

  static const char* value(const ::jaco_msgs::SetForceControlParams&) { return value(); }
};

template<>
struct DataType< ::jaco_msgs::SetForceControlParams > {
  static const char* value()
  {
    return "jaco_msgs/SetForceControlParams";
  }

  static const char* value(const ::jaco_msgs::SetForceControlParams&) { return value(); }
};


// service_traits::MD5Sum< ::jaco_msgs::SetForceControlParamsRequest> should match 
// service_traits::MD5Sum< ::jaco_msgs::SetForceControlParams > 
template<>
struct MD5Sum< ::jaco_msgs::SetForceControlParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jaco_msgs::SetForceControlParams >::value();
  }
  static const char* value(const ::jaco_msgs::SetForceControlParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaco_msgs::SetForceControlParamsRequest> should match 
// service_traits::DataType< ::jaco_msgs::SetForceControlParams > 
template<>
struct DataType< ::jaco_msgs::SetForceControlParamsRequest>
{
  static const char* value()
  {
    return DataType< ::jaco_msgs::SetForceControlParams >::value();
  }
  static const char* value(const ::jaco_msgs::SetForceControlParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jaco_msgs::SetForceControlParamsResponse> should match 
// service_traits::MD5Sum< ::jaco_msgs::SetForceControlParams > 
template<>
struct MD5Sum< ::jaco_msgs::SetForceControlParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jaco_msgs::SetForceControlParams >::value();
  }
  static const char* value(const ::jaco_msgs::SetForceControlParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jaco_msgs::SetForceControlParamsResponse> should match 
// service_traits::DataType< ::jaco_msgs::SetForceControlParams > 
template<>
struct DataType< ::jaco_msgs::SetForceControlParamsResponse>
{
  static const char* value()
  {
    return DataType< ::jaco_msgs::SetForceControlParams >::value();
  }
  static const char* value(const ::jaco_msgs::SetForceControlParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JACO_MSGS_MESSAGE_SETFORCECONTROLPARAMS_H
