"""autogenerated by genpy from jaco_msgs/ArmJointAnglesGoal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import jaco_msgs.msg

class ArmJointAnglesGoal(genpy.Message):
  _md5sum = "d86b424e9a65a92d0fef7f9d22a2b38f"
  _type = "jaco_msgs/ArmJointAnglesGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Goal
JointAngles angles

================================================================================
MSG: jaco_msgs/JointAngles
float32 joint1
float32 joint2
float32 joint3
float32 joint4
float32 joint5
float32 joint6

"""
  __slots__ = ['angles']
  _slot_types = ['jaco_msgs/JointAngles']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       angles

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ArmJointAnglesGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.angles is None:
        self.angles = jaco_msgs.msg.JointAngles()
    else:
      self.angles = jaco_msgs.msg.JointAngles()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.angles.joint1, _x.angles.joint2, _x.angles.joint3, _x.angles.joint4, _x.angles.joint5, _x.angles.joint6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.angles is None:
        self.angles = jaco_msgs.msg.JointAngles()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.angles.joint1, _x.angles.joint2, _x.angles.joint3, _x.angles.joint4, _x.angles.joint5, _x.angles.joint6,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.angles.joint1, _x.angles.joint2, _x.angles.joint3, _x.angles.joint4, _x.angles.joint5, _x.angles.joint6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.angles is None:
        self.angles = jaco_msgs.msg.JointAngles()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.angles.joint1, _x.angles.joint2, _x.angles.joint3, _x.angles.joint4, _x.angles.joint5, _x.angles.joint6,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6f = struct.Struct("<6f")
